// internal/storage/queries.go
package storage

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/logstream/internal/models"
)

// Search performs full-text search and filtering across the logs table.
// Uses the Trigram GIN index on the message column (via ILIKE) for blazing fast partial matches.
// A single query with COUNT(*) OVER() avoids scanning twice.
func (s *Store) Search(ctx context.Context, q, service, level string, from, to time.Time, limit, offset int) ([]models.LogEntry, int64, error) {
	var whereClauses []string
	var args []any
	argPos := 1

	// Use ILIKE because our custom pg_trgm GIN index makes this lightning fast
	// without breaking on technical strings like "NullPointerException" or "B-199"
	// Inside Search() and ListAlerts() functions

	if q != "" {
		// FIX: Replace literal spaces with wildcards to ignore syslog double-spacing
		fuzzyQ := strings.ReplaceAll(q, " ", "%")

		// For Search():
		whereClauses = append(whereClauses, fmt.Sprintf("message ILIKE $%d", argPos))

		// OR for ListAlerts() use the table alias 'l.':
		// whereClauses = append(whereClauses, fmt.Sprintf("l.message ILIKE $%d", argPos))

		args = append(args, "%"+fuzzyQ+"%")
		argPos++
	}
	if service != "" {
		whereClauses = append(whereClauses, fmt.Sprintf("service = $%d", argPos))
		args = append(args, service)
		argPos++
	}
	if level != "" {
		whereClauses = append(whereClauses, fmt.Sprintf("level = $%d", argPos))
		args = append(args, level)
		argPos++
	}
	if !from.IsZero() {
		whereClauses = append(whereClauses, fmt.Sprintf("timestamp >= $%d", argPos))
		args = append(args, from)
		argPos++
	}
	if !to.IsZero() {
		whereClauses = append(whereClauses, fmt.Sprintf("timestamp <= $%d", argPos))
		args = append(args, to)
		argPos++
	}

	whereSQL := ""
	if len(whereClauses) > 0 {
		whereSQL = "WHERE " + strings.Join(whereClauses, " AND ")
	}

	// Optimization 2 (Kept!): COUNT(*) OVER() gives total matching rows without a second scan.
	searchSQL := fmt.Sprintf(
		`SELECT id, timestamp, level, service, message, metadata, COUNT(*) OVER() AS total_count
         FROM logs %s
         ORDER BY timestamp DESC, id DESC
         LIMIT $%d OFFSET $%d`,
		whereSQL, argPos, argPos+1,
	)
	searchArgs := append(args, limit, offset)

	rows, err := s.pool.Query(ctx, searchSQL, searchArgs...)
	if err != nil {
		return nil, 0, fmt.Errorf("failed executing search logs query: %w", err)
	}
	defer rows.Close()

	var logs []models.LogEntry
	var totalCount int64
	for rows.Next() {
		var entry models.LogEntry
		// Scan the 7th column (totalCount) generated by the window function
		err := rows.Scan(&entry.ID, &entry.Timestamp, &entry.Level, &entry.Service, &entry.Message, &entry.Metadata, &totalCount)
		if err != nil {
			return nil, 0, fmt.Errorf("failed scanning log row: %w", err)
		}
		if entry.Metadata == nil {
			entry.Metadata = make(map[string]any)
		}
		logs = append(logs, entry)
	}

	if err = rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("error iterating log rows: %w", err)
	}

	return logs, totalCount, nil
}

// GetLog returns a single target log record matching the explicit ID
func (s *Store) GetLog(ctx context.Context, id int64) (*models.LogEntry, error) {
	var entry models.LogEntry
	query := "SELECT id, timestamp, level, service, message, metadata FROM logs WHERE id = $1"

	err := s.pool.QueryRow(ctx, query, id).Scan(
		&entry.ID, &entry.Timestamp, &entry.Level, &entry.Service, &entry.Message, &entry.Metadata,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("log record not found with id %d: %w", id, err)
		}
		return nil, fmt.Errorf("failed fetching log profile: %w", err)
	}

	if entry.Metadata == nil {
		entry.Metadata = make(map[string]any)
	}

	return &entry, nil
}

// Stats runs multi-dimensional data aggregations for historical trends and structural overview charts
func (s *Store) Stats(ctx context.Context, from, to time.Time) (*models.StatsResult, error) {
	res := &models.StatsResult{
		CountByLevel:   make(map[string]int64),
		CountByService: make(map[string]int64),
		LogsPerHour:    []models.HourCount{},
	}

	// Aggregation A: Log entries parsed by severe validation type levels
	levelQuery := "SELECT level, COUNT(*) FROM logs WHERE timestamp BETWEEN $1 AND $2 GROUP BY level"
	lRows, err := s.pool.Query(ctx, levelQuery, from, to)
	if err != nil {
		return nil, fmt.Errorf("failed compiling level metrics: %w", err)
	}
	defer lRows.Close()
	for lRows.Next() {
		var lvl string
		var count int64
		if err := lRows.Scan(&lvl, &count); err != nil {
			return nil, err
		}
		res.CountByLevel[lvl] = count
	}

	// Aggregation B: Top logs broken down across operational microservice tags
	serviceQuery := "SELECT service, COUNT(*) FROM logs WHERE timestamp BETWEEN $1 AND $2 GROUP BY service ORDER BY count DESC"
	sRows, err := s.pool.Query(ctx, serviceQuery, from, to)
	if err != nil {
		return nil, fmt.Errorf("failed compiling service metrics: %w", err)
	}
	defer sRows.Close()
	for sRows.Next() {
		var svc string
		var count int64
		if err := sRows.Scan(&svc, &count); err != nil {
			return nil, err
		}
		res.CountByService[svc] = count
	}

	// Aggregation C: Time-series bucketing truncated down to 1-hour slots
	hourQuery := `
		SELECT date_trunc('hour', timestamp) AS hour, COUNT(*) 
		FROM logs 
		WHERE timestamp BETWEEN $1 AND $2 
		GROUP BY hour 
		ORDER BY hour`
	hRows, err := s.pool.Query(ctx, hourQuery, from, to)
	if err != nil {
		return nil, fmt.Errorf("failed compiling time series hourly metrics: %w", err)
	}
	defer hRows.Close()
	for hRows.Next() {
		var hCount models.HourCount
		if err := hRows.Scan(&hCount.Hour, &hCount.Count); err != nil {
			return nil, err
		}
		res.LogsPerHour = append(res.LogsPerHour, hCount)
	}

	return res, nil
}

// ListServices collects a unique dictionary array of all actively registered system services
func (s *Store) ListServices(ctx context.Context) ([]string, error) {
	query := "SELECT DISTINCT service FROM logs ORDER BY service"
	rows, err := s.pool.Query(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("failed gathering unique service entries: %w", err)
	}
	defer rows.Close()

	var services []string
	for rows.Next() {
		var svc string
		if err := rows.Scan(&svc); err != nil {
			return nil, err
		}
		services = append(services, svc)
	}
	return services, nil
}

// --- Alert Rule CRUD ---

func (s *Store) ListRules(ctx context.Context) ([]models.AlertRule, error) {
	query := `SELECT id, name, pattern, level_filter, service_filter, cooldown_minutes, is_active, created_at 
			  FROM alert_rules ORDER BY created_at DESC`

	rows, err := s.pool.Query(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("failed to list rules: %w", err)
	}
	defer rows.Close()

	var rules []models.AlertRule
	for rows.Next() {
		var r models.AlertRule
		if err := rows.Scan(&r.ID, &r.Name, &r.Pattern, &r.LevelFilter, &r.ServiceFilter, &r.CooldownMinutes, &r.IsActive, &r.CreatedAt); err != nil {
			return nil, err
		}
		rules = append(rules, r)
	}
	return rules, nil
}

func (s *Store) GetRule(ctx context.Context, id uuid.UUID) (*models.AlertRule, error) {
	query := `SELECT id, name, pattern, level_filter, service_filter, cooldown_minutes, is_active, created_at 
			  FROM alert_rules WHERE id = $1`

	var r models.AlertRule
	err := s.pool.QueryRow(ctx, query, id).Scan(&r.ID, &r.Name, &r.Pattern, &r.LevelFilter, &r.ServiceFilter, &r.CooldownMinutes, &r.IsActive, &r.CreatedAt)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("rule not found: %w", err)
		}
		return nil, err
	}
	return &r, nil
}

func (s *Store) CreateRule(ctx context.Context, rule models.AlertRule) (*models.AlertRule, error) {
	query := `INSERT INTO alert_rules (name, pattern, level_filter, service_filter, cooldown_minutes, is_active) 
			  VALUES ($1, $2, $3, $4, $5, $6) 
			  RETURNING id, created_at`

	err := s.pool.QueryRow(ctx, query, rule.Name, rule.Pattern, rule.LevelFilter, rule.ServiceFilter, rule.CooldownMinutes, rule.IsActive).Scan(&rule.ID, &rule.CreatedAt)
	if err != nil {
		return nil, fmt.Errorf("failed to create rule: %w", err)
	}
	return &rule, nil
}

func (s *Store) UpdateRule(ctx context.Context, id uuid.UUID, rule models.AlertRule) (*models.AlertRule, error) {
	query := `UPDATE alert_rules 
			  SET name=$1, pattern=$2, level_filter=$3, service_filter=$4, cooldown_minutes=$5, is_active=$6 
			  WHERE id=$7 
			  RETURNING id, name, pattern, level_filter, service_filter, cooldown_minutes, is_active, created_at`

	var r models.AlertRule
	err := s.pool.QueryRow(ctx, query, rule.Name, rule.Pattern, rule.LevelFilter, rule.ServiceFilter, rule.CooldownMinutes, rule.IsActive, id).Scan(
		&r.ID, &r.Name, &r.Pattern, &r.LevelFilter, &r.ServiceFilter, &r.CooldownMinutes, &r.IsActive, &r.CreatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to update rule: %w", err)
	}
	return &r, nil
}

func (s *Store) DeleteRule(ctx context.Context, id uuid.UUID) error {
	tag, err := s.pool.Exec(ctx, "DELETE FROM alert_rules WHERE id = $1", id)
	if err != nil {
		return fmt.Errorf("failed to delete rule: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("rule not found")
	}
	return nil
}

// --- Alert History ---

func (s *Store) CreateAlert(ctx context.Context, ruleID uuid.UUID, logID int64, logTimestamp time.Time) error {
	query := `INSERT INTO alerts (rule_id, log_id, log_timestamp) VALUES ($1, $2, $3)`
	_, err := s.pool.Exec(ctx, query, ruleID, logID, logTimestamp)
	return err
}

func (s *Store) ListAlerts(ctx context.Context, ruleID, q, service, level string, from, to time.Time, limit, offset int) ([]models.AlertWithContext, int64, error) {
	var whereClauses []string
	var args []any
	argPos := 1

	if ruleID != "" {
		whereClauses = append(whereClauses, fmt.Sprintf("a.rule_id = $%d", argPos))
		args = append(args, ruleID)
		argPos++
	}
	if q != "" {
		// Space-fuzzy matching for the alerts search bar too!
		fuzzyQ := strings.ReplaceAll(q, " ", "%")
		whereClauses = append(whereClauses, fmt.Sprintf("l.message ILIKE $%d", argPos))
		args = append(args, "%"+fuzzyQ+"%")
		argPos++
	}
	if service != "" {
		whereClauses = append(whereClauses, fmt.Sprintf("l.service = $%d", argPos))
		args = append(args, service)
		argPos++
	}
	if level != "" {
		whereClauses = append(whereClauses, fmt.Sprintf("l.level = $%d", argPos))
		args = append(args, level)
		argPos++
	}
	if !from.IsZero() {
		whereClauses = append(whereClauses, fmt.Sprintf("a.fired_at >= $%d", argPos))
		args = append(args, from)
		argPos++
	}
	if !to.IsZero() {
		whereClauses = append(whereClauses, fmt.Sprintf("a.fired_at <= $%d", argPos))
		args = append(args, to)
		argPos++
	}

	whereSQL := ""
	if len(whereClauses) > 0 {
		whereSQL = "WHERE " + strings.Join(whereClauses, " AND ")
	}

	// Use COUNT(*) OVER() to grab the true total of matching rows in one pass
	query := fmt.Sprintf(`
        SELECT a.id, a.rule_id, a.log_id, a.fired_at, 
               r.name AS rule_name, r.pattern, 
               l.level, l.service, l.message,
               COUNT(*) OVER() AS total_count
        FROM alerts a
        JOIN alert_rules r ON a.rule_id = r.id
        JOIN logs l ON a.log_id = l.id AND a.log_timestamp = l.timestamp
        %s
        ORDER BY a.fired_at DESC
        LIMIT $%d OFFSET $%d`, whereSQL, argPos, argPos+1)

	args = append(args, limit, offset)

	rows, err := s.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to list alerts: %w", err)
	}
	defer rows.Close()

	var alerts []models.AlertWithContext
	var totalCount int64
	for rows.Next() {
		var a models.AlertWithContext
		// Scan the newly added totalCount
		if err := rows.Scan(&a.ID, &a.RuleID, &a.LogID, &a.FiredAt, &a.RuleName, &a.Pattern, &a.Level, &a.Service, &a.Message, &totalCount); err != nil {
			return nil, 0, err
		}
		alerts = append(alerts, a)
	}
	return alerts, totalCount, nil
}
